services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true  # Enable basic authentication
      - N8N_BASIC_AUTH_USER=${N8N_USER}  # Set the username from the environment variable
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}  # Set the password from the environment variable
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - N8N_PUBLIC_URL=http://localhost:5678
      - NODE_ENV=production
    volumes:
      - ./n8n_data:/home/node/.n8n

volumes:
  n8n_data:
